# -*- coding: utf-8 -*-
"""Formatação de saida.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18bOdVrj8oL3vERYMCcwn6eP3G-v-8tOn
"""

#imprimir hora e minutos na tela
hora = 10
minutos = 26
segundos = 18
print(f'{hora} : {minutos} : {segundos}')